/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => RandomNoteDraw
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  excludeFolders: "",
  dailyOnly: false,
  avoidRepeat: true,
  openInNewTab: false,
  logEnabled: true,
  logPath: "Random Notes/\u6253\u5361\u8BB0\u5F55.md"
};
var DAILY_NOTE_PATTERN = /^\d{4}-\d{2}-\d{2}/;
var CAT_COUNT = 20;
function formatNow() {
  const d = new Date();
  const p = (n) => String(n).padStart(2, "0");
  return `${d.getFullYear()}-${p(d.getMonth() + 1)}-${p(d.getDate())} ${p(d.getHours())}:${p(d.getMinutes())}`;
}
var RandomNoteDraw = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.lastOpened = null;
  }
  async onload() {
    await this.loadSettings();
    this.addRibbonIcon("dice", "\u62BD\u4E00\u5F20\u968F\u673A\u7B14\u8BB0", () => {
      this.drawRandomNote();
    });
    this.addCommand({
      id: "draw-random-note",
      name: "\u62BD\u4E00\u5F20\u968F\u673A\u7B14\u8BB0",
      callback: () => this.drawRandomNote()
    });
    this.addSettingTab(new RandomNoteDrawSettingTab(this.app, this));
  }
  onunload() {
  }
  /** 入口：从候选笔记中抽一张并打开像素风弹窗 */
  drawRandomNote() {
    const candidates = this.getCandidateNotes();
    if (candidates.length === 0) {
      new import_obsidian.Notice("\u6CA1\u6709\u7B26\u5408\u6761\u4EF6\u7684\u7B14\u8BB0\u53EF\u62BD");
      return;
    }
    new DrawModal(this.app, this).open();
  }
  /** 在候选笔记中随机选一张（考虑避免连抽同一篇） */
  pickNote(candidates) {
    let pick = candidates[Math.floor(Math.random() * candidates.length)];
    if (this.settings.avoidRepeat && candidates.length > 1) {
      let attempts = 0;
      while (pick.path === this.lastOpened && attempts < 10) {
        pick = candidates[Math.floor(Math.random() * candidates.length)];
        attempts++;
      }
    }
    this.lastOpened = pick.path;
    return pick;
  }
  /** 打开一篇笔记 */
  openNote(file) {
    const leaf = this.settings.openInNewTab ? this.app.workspace.getLeaf("tab") : this.app.workspace.getLeaf(false);
    leaf.openFile(file);
  }
  getCandidateNotes() {
    let files = this.app.vault.getMarkdownFiles();
    const excludes = this.settings.excludeFolders.split(/[,，]/).map((s) => s.trim().replace(/\/+$/, "")).filter((s) => s.length > 0);
    if (excludes.length > 0) {
      files = files.filter(
        (f) => !excludes.some(
          (dir) => f.path === dir || f.path.startsWith(dir + "/")
        )
      );
    }
    if (this.settings.dailyOnly) {
      files = files.filter((f) => DAILY_NOTE_PATTERN.test(f.basename));
    }
    return files;
  }
  /** 抽到后自动打卡：在记录文件末尾追加一行 */
  async logDraw(file) {
    if (!this.settings.logEnabled)
      return;
    const path = this.settings.logPath.trim() || DEFAULT_SETTINGS.logPath;
    const folder = path.split("/").slice(0, -1).join("/");
    const folderLabel = file.parent && file.parent.path !== "/" ? `\uFF08${file.parent.path}\uFF09` : "";
    const line = `- ${formatNow()} \xB7 [[${file.basename}]]${folderLabel}`;
    const existing = this.app.vault.getAbstractFileByPath(path);
    if (existing instanceof import_obsidian.TFile) {
      await this.app.vault.process(existing, (data) => {
        const base = data.trimEnd();
        return base ? base + "\n" + line + "\n" : line + "\n";
      });
    } else {
      if (folder) {
        await this.ensureFolder(folder);
      }
      const header = `# \u968F\u673A\u62BD\u5361\u6253\u5361\u8BB0\u5F55

> \u6BCF\u6B21\u62BD\u5361\u81EA\u52A8\u8BB0\u5F55\uFF0C\u65F6\u95F4 \xB7 \u62BD\u5230\u7684\u7B14\u8BB0\u3002

`;
      await this.app.vault.create(path, header + line + "\n");
    }
  }
  async ensureFolder(path) {
    const parts = path.split("/");
    let cur = "";
    for (const part of parts) {
      cur = cur ? `${cur}/${part}` : part;
      if (!this.app.vault.getAbstractFileByPath(cur)) {
        await this.app.vault.createFolder(cur);
      }
    }
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
var DrawModal = class extends import_obsidian.Modal {
  constructor(app, plugin) {
    super(app);
    this.lastVariant = -1;
    this.current = null;
    this.plugin = plugin;
  }
  onOpen() {
    this.titleEl.setText("RANDOM NOTE DRAW");
    this.modalEl.addClass("rnd-modal");
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("rnd-content");
    contentEl.createDiv({ cls: "rnd-header", text: "\u2605 \u968F\u673A\u62BD\u5361 \u2605" });
    const wrap = contentEl.createDiv({ cls: "rnd-card-wrap" });
    this.card = wrap.createDiv({ cls: "rnd-card" });
    const back = this.card.createDiv({ cls: "rnd-face rnd-back" });
    back.createDiv({ cls: "rnd-question", text: "?" });
    this.runGuy = back.createDiv({ cls: "rnd-cat-img rnd-cat-back" });
    const front = this.card.createDiv({ cls: "rnd-face rnd-front" });
    this.cheerGuy = front.createDiv({ cls: "rnd-cat-img rnd-cat-front" });
    this.titleView = front.createDiv({ cls: "rnd-title" });
    this.folderView = front.createDiv({ cls: "rnd-folder" });
    const btns = contentEl.createDiv({ cls: "rnd-buttons" });
    btns.createEl("button", { cls: "rnd-btn rnd-btn-primary", text: "\u6253\u5F00\u7B14\u8BB0" }).addEventListener("click", () => this.openCurrent());
    btns.createEl("button", { cls: "rnd-btn", text: "\u518D\u62BD\u4E00\u5F20" }).addEventListener("click", () => this.draw());
    btns.createEl("button", { cls: "rnd-btn", text: "\u5173\u95ED" }).addEventListener("click", () => this.close());
    this.statusView = contentEl.createDiv({ cls: "rnd-status", text: "\u6D17\u724C\u4E2D\u2026" });
    this.draw();
  }
  /** 抽一张并执行翻卡动画，同时自动打卡 */
  draw() {
    const candidates = this.plugin.getCandidateNotes();
    if (candidates.length === 0) {
      new import_obsidian.Notice("\u6CA1\u6709\u7B26\u5408\u6761\u4EF6\u7684\u7B14\u8BB0\u53EF\u62BD");
      return;
    }
    this.current = this.plugin.pickNote(candidates);
    this.applyRandomCat();
    this.card.removeClass("revealed");
    this.statusView.setText("\u6D17\u724C\u4E2D\u2026");
    window.setTimeout(() => {
      if (!this.current)
        return;
      this.titleView.setText(this.current.basename);
      const folder = this.current.parent && this.current.parent.path !== "/" ? this.current.parent.path : "\u6839\u76EE\u5F55";
      this.folderView.setText(folder);
      this.card.addClass("revealed");
      this.statusView.setText("\u62BD\u5230\u5566\uFF01");
      this.plugin.logDraw(this.current);
    }, 650);
  }
  /** 每次抽卡随机换一只小猫（避免连续两次同款） */
  applyRandomCat() {
    let idx = Math.floor(Math.random() * CAT_COUNT) + 1;
    if (CAT_COUNT > 1) {
      let attempts = 0;
      while (idx === this.lastVariant && attempts < 10) {
        idx = Math.floor(Math.random() * CAT_COUNT) + 1;
        attempts++;
      }
    }
    for (let i = 1; i <= CAT_COUNT; i++) {
      const cls = `rnd-cat-${String(i).padStart(2, "0")}`;
      this.runGuy.removeClass(cls);
      this.cheerGuy.removeClass(cls);
    }
    const chosen = `rnd-cat-${String(idx).padStart(2, "0")}`;
    this.runGuy.addClass(chosen);
    this.cheerGuy.addClass(chosen);
    this.lastVariant = idx;
  }
  openCurrent() {
    if (!this.current)
      return;
    this.plugin.openNote(this.current);
    this.close();
  }
  onClose() {
    this.contentEl.empty();
  }
};
var RandomNoteDrawSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("\u6392\u9664\u7684\u6587\u4EF6\u5939").setDesc(
      "\u9017\u53F7\uFF08\u4E2D\u82F1\u6587\u5747\u53EF\uFF09\u5206\u9694\u7684\u6587\u4EF6\u5939\u8DEF\u5F84\uFF0C\u8FD9\u4E9B\u6587\u4EF6\u5939\u5185\u7684\u7B14\u8BB0\u4E0D\u4F1A\u88AB\u62BD\u5230\u3002\u4F8B\u5982\uFF1ATemplates, Attachments/Images"
    ).addText(
      (text) => text.setPlaceholder("Templates, Attachments").setValue(this.plugin.settings.excludeFolders).onChange(async (value) => {
        this.plugin.settings.excludeFolders = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u53EA\u62BD\u6BCF\u65E5\u7B14\u8BB0").setDesc("\u53EA\u62BD\u53D6\u6587\u4EF6\u540D\u4EE5 YYYY-MM-DD \u5F00\u5934\u7684\u7B14\u8BB0\uFF08\u9ED8\u8BA4\u65E5\u8BB0\u547D\u540D\u683C\u5F0F\uFF09\u3002").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.dailyOnly).onChange(async (value) => {
        this.plugin.settings.dailyOnly = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u907F\u514D\u8FDE\u7EED\u62BD\u5230\u540C\u4E00\u7BC7").setDesc("\u5F00\u542F\u540E\u4E0D\u4F1A\u8FDE\u7EED\u4E24\u6B21\u6253\u5F00\u540C\u4E00\u7BC7\u7B14\u8BB0\uFF08\u7B14\u8BB0\u4E0D\u8DB3\u4E24\u7BC7\u65F6\u9664\u5916\uFF09\u3002").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.avoidRepeat).onChange(async (value) => {
        this.plugin.settings.avoidRepeat = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u5728\u65B0\u6807\u7B7E\u9875\u6253\u5F00").setDesc("\u5F00\u542F\u540E\u62BD\u5230\u7684\u7B14\u8BB0\u5728\u65B0\u6807\u7B7E\u9875\u6253\u5F00\uFF0C\u5426\u5219\u5728\u5F53\u524D\u7684\u6807\u7B7E\u9875\u6253\u5F00\u3002").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.openInNewTab).onChange(async (value) => {
        this.plugin.settings.openInNewTab = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u62BD\u5361\u6253\u5361\u8BB0\u5F55").setDesc("\u6BCF\u6B21\u62BD\u5230\u7B14\u8BB0\u65F6\uFF0C\u81EA\u52A8\u5728\u8BB0\u5F55\u6587\u4EF6\u4E2D\u8FFD\u52A0\u4E00\u6761\u6253\u5361\u3002").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.logEnabled).onChange(async (value) => {
        this.plugin.settings.logEnabled = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u8BB0\u5F55\u6587\u4EF6\u8DEF\u5F84").setDesc("\u6253\u5361\u8BB0\u5F55\u4FDD\u5B58\u4E3A Markdown \u6587\u4EF6\uFF0C\u9996\u6B21\u62BD\u5361\u65F6\u81EA\u52A8\u521B\u5EFA\uFF08\u542B\u6240\u5728\u6587\u4EF6\u5939\uFF09\u3002").addText(
      (text) => text.setPlaceholder(DEFAULT_SETTINGS.logPath).setValue(this.plugin.settings.logPath).onChange(async (value) => {
        this.plugin.settings.logPath = value;
        await this.plugin.saveSettings();
      })
    );
  }
};
